server:
  port: 9090
spring:
  application:
    name: shiro-vue-demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro_vue_demo?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
  redis:
    password: 123456
    host: localhost
    port: 6379
